---
- name: install openssh
  pacman:
    name: openssh
    state: present

- name: configure SSHD
  lineinfile:
    path: /etc/ssh/sshd_config
    regexp: '^#PermitRootLogin'
    line: 'PermitRootLogin no'
  notify: restart sshd

- meta: flush_handlers
