---
- name: install containers packages
  pacman:
    name:
      - docker          # high level container runtime
      - docker-compose  # multi-container docker apps
      - podman          # docker alternative without dockerd
      - podman-compose  # docker-compose for podman
      # https://github.com/kubernetes-sigs/krew

- name: copy subuid files for podman rootless
  template:
    src: subuid.j2
    dest: /etc/subuid

- name: copy subgid files for podman rootless
  template:
    src: subgid.j2
    dest: /etc/subgid

- name: configure podman registries
  copy:
    src: registries.conf
    dest: /etc/containers/

- name: configure podman storage
  copy:
    src: storage.conf
    dest: /etc/containers/

- name: Add user to docker group
  user:
    name: '{{ user }}'
    groups: docker
    append: yes
