---
- name: install desktop packages
  pacman:
    name:
      - plasma-desktop
      - dolphin
      - konsole
      - appstream-qt6
      - xdg-user-dirs
      - xdg-desktop-portal-kde
    state: present

- name: install video packages
  pacman:
    name:
      - mesa
      - mesa-demos
      - lib32-virtualgl
      - vulkan-radeon
      - lib32-vulkan-radeon
      - libva-utils
    state: present

- name: install audio packages
  pacman:
    name:
      - pipewire
      - pipewire-pulse
      - pipewire-alsa
      - wireplumber
      - alsa-utils
    state: present

- name: install applications packages
  pacman:
    name:
      - kitty # terminal emulator
    state: present

- name: add missing gpg keys for aur
  become: no
  shell: gpg --recv '{{item}}'
  loop:
    - F4B432D5D67990E3 # wob

  changed_when: false

- name: install aur packages
  become: no
  aur:
    skip_installed: true
    name:
      - thorium-browser-bin
      - downgrade # package downgrader
