---
- name: install desktop packages
  pacman:
    name:
      - hyprland
      - hyprlock
    state: present

- name: install video packages
  pacman:
    name:
      - mesa
      - mesa-demos
      - vulkan-radeon
      - libva-utils
    state: present

- name: install audio packages
  pacman:
    name:
      - pipewire
      - pipewire-pulse
      - pipewire-alsa
      - wireplumber
      - pavucontrol
      - pamixer
    state: present

- name: install applications packages
  pacman:
    name:
      - kitty # terminal emulator
      - evince # pdf viewer
      - evolution # mail client
      - gnome-keyring # evolution gnome keyring
      - seahorse # keyring manager
      - firefox
      - firefox-i18n-fr
      - flatpak # package manager
      - gimp # img editor
      - mpv # video player
      - rdesktop # remote desktop client
      - remmina # remote desktop client
      - freerdp # remmina dep for rdp
      - qbittorrent
    state: present

- name: add missing gpg keys for aur
  become: no
  shell: gpg --recv '{{item}}'
  loop:
    - F4B432D5D67990E3 # wob

  changed_when: false

- name: install aur packages
  become: no
  aur:
    skip_installed: true
    name:
      #- gnome-ssh-askpass2 # ssh askpass gui
      - downgrade # package downgrader
      - lf # cli file manager
      - otf-font-awesome
