---
- name: configure zfs auto snapshot
  shell: |
    zfs set com.sun:auto-snapshot=false zroot
    zfs set com.sun:auto-snapshot=false zroot/data
    zfs set com.sun:auto-snapshot=false zroot/ROOT
    zfs set com.sun:auto-snapshot=false zroot/data
    zfs set com.sun:auto-snapshot=true zroot/data/home
    zfs set com.sun:auto-snapshot=true zroot/ROOT/archlinux
    zfs set com.sun:auto-snapshot:frequent=false zroot/data/home
    zfs set com.sun:auto-snapshot:monthly=false zroot/data/home
    zfs set com.sun:auto-snapshot:hourly=false zroot/data/home
    zfs set com.sun:auto-snapshot:weekly=false zroot/data/home
    zfs set com.sun:auto-snapshot:daily=true zroot/data/home
    zfs set com.sun:auto-snapshot=true zroot/data/home
    zfs set com.sun:auto-snapshot:frequent=false zroot/ROOT/archlinux
    zfs set com.sun:auto-snapshot:monthly=false zroot/ROOT/archlinux
    zfs set com.sun:auto-snapshot:hourly=false zroot/ROOT/archlinux
    zfs set com.sun:auto-snapshot:weekly=false zroot/ROOT/archlinux
    zfs set com.sun:auto-snapshot:daily=true zroot/ROOT/archlinux
    zfs set com.sun:auto-snapshot=true zroot/ROOT/archlinux

- name: setup daily zfs scrub
  copy:
    src: zscrub
    dest: /etc/cron.weekly/
    mode: 0755
