---
- name: install virt packages
  pacman:
    name:
      - qemu-base
      - libvirt
      - virt-manager
      - ebtables
      - dnsmasq
      - ovmf
      - podman
      - distrobox
      - incus
  notify: restart libvirt

- name: add user to libvirt group
  user:
    name: '{{user}}'
    groups: libvirt
    append: yes

- name: enable nested virtualization
  copy:
    dest: /etc/modprobe.d/kvm.conf
    content: |
      options kvm_intel nested=1
